import enum
from typing import Generator, Union

class Style(enum.IntEnum):
    GOOGLE = ...
    NUMPY = ...
    PLAIN = ...

class SyntaxKind(enum.IntEnum):
    # Common tokens
    NAME = ...
    TYPE = ...
    COLON = ...
    DESCRIPTION = ...
    OPEN_BRACKET = ...
    CLOSE_BRACKET = ...
    OPTIONAL = ...
    BODY_TEXT = ...
    SUMMARY = ...
    EXTENDED_SUMMARY = ...
    STRAY_LINE = ...
    # Google-specific tokens
    WARNING_TYPE = ...
    # NumPy-specific tokens
    UNDERLINE = ...
    DIRECTIVE_MARKER = ...
    KEYWORD = ...
    DOUBLE_COLON = ...
    VERSION = ...
    RETURN_TYPE = ...
    DEFAULT_KEYWORD = ...
    DEFAULT_SEPARATOR = ...
    DEFAULT_VALUE = ...
    NUMBER = ...
    CONTENT = ...
    # Google nodes
    GOOGLE_DOCSTRING = ...
    GOOGLE_SECTION = ...
    GOOGLE_SECTION_HEADER = ...
    GOOGLE_ARG = ...
    GOOGLE_RETURNS = ...
    GOOGLE_EXCEPTION = ...
    GOOGLE_WARNING = ...
    GOOGLE_SEE_ALSO_ITEM = ...
    GOOGLE_ATTRIBUTE = ...
    GOOGLE_METHOD = ...
    # NumPy nodes
    NUMPY_DOCSTRING = ...
    NUMPY_SECTION = ...
    NUMPY_SECTION_HEADER = ...
    NUMPY_DEPRECATION = ...
    NUMPY_PARAMETER = ...
    NUMPY_RETURNS = ...
    NUMPY_EXCEPTION = ...
    NUMPY_WARNING = ...
    NUMPY_SEE_ALSO_ITEM = ...
    NUMPY_REFERENCE = ...
    NUMPY_ATTRIBUTE = ...
    NUMPY_METHOD = ...
    # Plain node
    PLAIN_DOCSTRING = ...

class TextRange:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...

class LineColumn:
    """A line/column position in the source text.

    ``lineno`` is 1-based; ``col`` is 0-based and counted in Unicode
    codepoints, matching Python's ``ast`` module convention.
    """
    @property
    def lineno(self) -> int: ...
    @property
    def col(self) -> int: ...

class Token:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def text(self) -> str: ...
    @property
    def range(self) -> TextRange: ...

class Node:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def range(self) -> TextRange: ...
    @property
    def children(self) -> list[Union[Node, Token]]: ...

# ─── Google ──────────────────────────────────────────────────────────────────

class GoogleArg:
    @property
    def name(self) -> Token: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...

class GoogleReturns:
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class GoogleException:
    @property
    def type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class GoogleSection:
    @property
    def kind(self) -> str: ...
    @property
    def args(self) -> list[GoogleArg]: ...
    @property
    def returns(self) -> GoogleReturns | None: ...
    @property
    def exceptions(self) -> list[GoogleException]: ...
    @property
    def body_text(self) -> Token | None: ...
    @property
    def node(self) -> Node: ...

class GoogleDocstring:
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def sections(self) -> list[GoogleSection]: ...
    @property
    def node(self) -> Node: ...
    @property
    def source(self) -> str: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def line_col(self, offset: int) -> LineColumn:
        """Convert a byte offset to a LineColumn.

        The offset is typically ``token.range.start`` or ``token.range.end``.
        ``lineno`` is 1-based; ``col`` is 0-based Unicode codepoints.
        """
        ...

# ─── NumPy ───────────────────────────────────────────────────────────────────

class NumPyParameter:
    @property
    def names(self) -> list[Token]: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...
    @property
    def default_value(self) -> Token | None: ...

class NumPyReturns:
    @property
    def name(self) -> Token | None: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class NumPyException:
    @property
    def type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class NumPySection:
    @property
    def kind(self) -> str: ...
    @property
    def parameters(self) -> list[NumPyParameter]: ...
    @property
    def returns(self) -> list[NumPyReturns]: ...
    @property
    def exceptions(self) -> list[NumPyException]: ...
    @property
    def body_text(self) -> Token | None: ...
    @property
    def node(self) -> Node: ...

class NumPyDocstring:
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def sections(self) -> list[NumPySection]: ...
    @property
    def node(self) -> Node: ...
    @property
    def source(self) -> str: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def line_col(self, offset: int) -> LineColumn:
        """Convert a byte offset to a LineColumn.

        The offset is typically ``token.range.start`` or ``token.range.end``.
        ``lineno`` is 1-based; ``col`` is 0-based Unicode codepoints.
        """
        ...

# ─── Model IR ────────────────────────────────────────────────────────────────

class Deprecation:
    version: str
    description: str | None
    def __init__(
        self,
        version: str,
        *,
        description: str | None = None,
    ) -> None: ...

class Parameter:
    names: list[str]
    type_annotation: str | None
    description: str | None
    is_optional: bool
    default_value: str | None
    def __init__(
        self,
        names: list[str],
        *,
        type_annotation: str | None = None,
        description: str | None = None,
        is_optional: bool = False,
        default_value: str | None = None,
    ) -> None: ...

class Return:
    name: str | None
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        *,
        name: str | None = None,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...

class ExceptionEntry:
    type_name: str
    description: str | None
    def __init__(
        self,
        type_name: str,
        *,
        description: str | None = None,
    ) -> None: ...

class SeeAlsoEntry:
    names: list[str]
    description: str | None
    def __init__(
        self,
        names: list[str],
        *,
        description: str | None = None,
    ) -> None: ...

class Reference:
    number: str | None
    content: str | None
    def __init__(
        self,
        *,
        number: str | None = None,
        content: str | None = None,
    ) -> None: ...

class Attribute:
    name: str
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        name: str,
        *,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...

class Method:
    name: str
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        name: str,
        *,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...

class Section:
    @property
    def kind(self) -> str: ...
    @property
    def parameters(self) -> list[Parameter]: ...
    @property
    def returns(self) -> list[Return]: ...
    @property
    def exceptions(self) -> list[ExceptionEntry]: ...
    @property
    def attributes(self) -> list[Attribute]: ...
    @property
    def methods(self) -> list[Method]: ...
    @property
    def see_also_entries(self) -> list[SeeAlsoEntry]: ...
    @property
    def references(self) -> list[Reference]: ...
    @property
    def body(self) -> str | None: ...
    def __init__(
        self,
        kind: str,
        *,
        parameters: list[Parameter] | None = None,
        returns: list[Return] | None = None,
        exceptions: list[ExceptionEntry] | None = None,
        attributes: list[Attribute] | None = None,
        methods: list[Method] | None = None,
        see_also_entries: list[SeeAlsoEntry] | None = None,
        references: list[Reference] | None = None,
        body: str | None = None,
    ) -> None: ...

class Docstring:
    summary: str | None
    extended_summary: str | None
    @property
    def deprecation(self) -> Deprecation | None: ...
    @deprecation.setter
    def deprecation(self, value: Deprecation | None) -> None: ...
    @property
    def sections(self) -> list[Section]: ...
    @sections.setter
    def sections(self, value: list[Section]) -> None: ...
    def __init__(
        self,
        *,
        summary: str | None = None,
        extended_summary: str | None = None,
        deprecation: Deprecation | None = None,
        sections: list[Section] | None = None,
    ) -> None: ...

# ─── Functions ───────────────────────────────────────────────────────────────

def parse_google(input: str) -> GoogleDocstring: ...
def parse_numpy(input: str) -> NumPyDocstring: ...
def parse_plain(input: str) -> PlainDocstring: ...
def detect_style(input: str) -> Style: ...
def emit_google(doc: Docstring, base_indent: int = 0) -> str: ...
def emit_numpy(doc: Docstring, base_indent: int = 0) -> str: ...
def walk(node: Node) -> Generator[Node | Token, None, None]: ...
