import enum
from typing import Iterator, Union

class Style(enum.IntEnum):
    GOOGLE = ...
    NUMPY = ...
    PLAIN = ...

class SyntaxKind(enum.IntEnum):
    # Common tokens
    NAME = ...
    TYPE = ...
    COLON = ...
    DESCRIPTION = ...
    OPEN_BRACKET = ...
    CLOSE_BRACKET = ...
    OPTIONAL = ...
    BODY_TEXT = ...
    SUMMARY = ...
    EXTENDED_SUMMARY = ...
    STRAY_LINE = ...
    # Google-specific tokens
    WARNING_TYPE = ...
    # NumPy-specific tokens
    UNDERLINE = ...
    DIRECTIVE_MARKER = ...
    KEYWORD = ...
    DOUBLE_COLON = ...
    VERSION = ...
    RETURN_TYPE = ...
    DEFAULT_KEYWORD = ...
    DEFAULT_SEPARATOR = ...
    DEFAULT_VALUE = ...
    NUMBER = ...
    CONTENT = ...
    # Google nodes
    GOOGLE_DOCSTRING = ...
    GOOGLE_SECTION = ...
    GOOGLE_SECTION_HEADER = ...
    GOOGLE_ARG = ...
    GOOGLE_RETURNS = ...
    GOOGLE_YIELDS = ...
    GOOGLE_EXCEPTION = ...
    GOOGLE_WARNING = ...
    GOOGLE_SEE_ALSO_ITEM = ...
    GOOGLE_ATTRIBUTE = ...
    GOOGLE_METHOD = ...
    # NumPy nodes
    NUMPY_DOCSTRING = ...
    NUMPY_SECTION = ...
    NUMPY_SECTION_HEADER = ...
    NUMPY_DEPRECATION = ...
    NUMPY_PARAMETER = ...
    NUMPY_RETURNS = ...
    NUMPY_YIELDS = ...
    NUMPY_EXCEPTION = ...
    NUMPY_WARNING = ...
    NUMPY_SEE_ALSO_ITEM = ...
    NUMPY_REFERENCE = ...
    NUMPY_ATTRIBUTE = ...
    NUMPY_METHOD = ...
    # Plain node
    PLAIN_DOCSTRING = ...

class TextRange:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...

class LineColumn:
    """A line/column position in the source text.

    ``lineno`` is 1-based; ``col`` is 0-based and counted in Unicode
    codepoints, matching Python's ``ast`` module convention.
    """
    @property
    def lineno(self) -> int: ...
    @property
    def col(self) -> int: ...

class Token:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def text(self) -> str: ...
    @property
    def range(self) -> TextRange: ...

class Node:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def range(self) -> TextRange: ...
    @property
    def children(self) -> list[Union[Node, Token]]: ...

# ─── Google ──────────────────────────────────────────────────────────────────

class GoogleArg:
    @classmethod
    def cast(cls, node: Node) -> GoogleArg | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def name(self) -> Token: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...

class GoogleReturns:
    @classmethod
    def cast(cls, node: Node) -> GoogleReturns | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class GoogleYields:
    @classmethod
    def cast(cls, node: Node) -> GoogleYields | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class GoogleException:
    @classmethod
    def cast(cls, node: Node) -> GoogleException | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class GoogleWarning:
    @classmethod
    def cast(cls, node: Node) -> GoogleWarning | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def warning_type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class GoogleSeeAlsoItem:
    @classmethod
    def cast(cls, node: Node) -> GoogleSeeAlsoItem | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def names(self) -> list[Token]: ...
    @property
    def description(self) -> Token | None: ...

class GoogleAttribute:
    @classmethod
    def cast(cls, node: Node) -> GoogleAttribute | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def name(self) -> Token: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class GoogleMethod:
    @classmethod
    def cast(cls, node: Node) -> GoogleMethod | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def name(self) -> Token: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class GoogleSection:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def section_kind(self) -> GoogleSectionKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def header_name(self) -> Token | None: ...
    def args(self) -> list[GoogleArg]: ...
    def returns(self) -> list[GoogleReturns]: ...
    def yields(self) -> list[GoogleYields]: ...
    def exceptions(self) -> list[GoogleException]: ...
    def warnings(self) -> list[GoogleWarning]: ...
    def see_also_items(self) -> list[GoogleSeeAlsoItem]: ...
    def attributes(self) -> list[GoogleAttribute]: ...
    def methods(self) -> list[GoogleMethod]: ...
    def body_text(self) -> Token | None: ...

class GoogleDocstring:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def style(self) -> Style: ...
    @property
    def node(self) -> Node: ...
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def source(self) -> str: ...
    def sections(self) -> list[GoogleSection]: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def walk(self) -> DocstringWalker: ...
    def line_col(self, offset: int) -> LineColumn:
        """Convert a byte offset to a LineColumn.

        The offset is typically ``token.range.start`` or ``token.range.end``.
        ``lineno`` is 1-based; ``col`` is 0-based Unicode codepoints.
        """
        ...

# ─── NumPy ───────────────────────────────────────────────────────────────────

class NumPyParameter:
    @classmethod
    def cast(cls, node: Node) -> NumPyParameter | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def names(self) -> list[Token]: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...
    @property
    def default_value(self) -> Token | None: ...

class NumPyReturns:
    @classmethod
    def cast(cls, node: Node) -> NumPyReturns | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def name(self) -> Token | None: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class NumPyYields:
    @classmethod
    def cast(cls, node: Node) -> NumPyYields | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def name(self) -> Token | None: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class NumPyException:
    @classmethod
    def cast(cls, node: Node) -> NumPyException | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class NumPyDeprecation:
    @classmethod
    def cast(cls, node: Node) -> NumPyDeprecation | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def version(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class NumPyWarning:
    @classmethod
    def cast(cls, node: Node) -> NumPyWarning | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class NumPySeeAlsoItem:
    @classmethod
    def cast(cls, node: Node) -> NumPySeeAlsoItem | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def names(self) -> list[Token]: ...
    @property
    def description(self) -> Token | None: ...

class NumPyReference:
    @classmethod
    def cast(cls, node: Node) -> NumPyReference | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def number(self) -> Token | None: ...
    @property
    def content(self) -> Token | None: ...

class NumPyAttribute:
    @classmethod
    def cast(cls, node: Node) -> NumPyAttribute | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def name(self) -> Token: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class NumPyMethod:
    @classmethod
    def cast(cls, node: Node) -> NumPyMethod | None: ...
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def name(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class NumPySection:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def section_kind(self) -> NumPySectionKind: ...
    @property
    def node(self) -> Node: ...
    @property
    def header_name(self) -> Token | None: ...
    def parameters(self) -> list[NumPyParameter]: ...
    def returns(self) -> list[NumPyReturns]: ...
    def yields(self) -> list[NumPyYields]: ...
    def exceptions(self) -> list[NumPyException]: ...
    def warnings(self) -> list[NumPyWarning]: ...
    def see_also_items(self) -> list[NumPySeeAlsoItem]: ...
    def references(self) -> list[NumPyReference]: ...
    def attributes(self) -> list[NumPyAttribute]: ...
    def methods(self) -> list[NumPyMethod]: ...
    def body_text(self) -> Token | None: ...

class NumPyDocstring:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def style(self) -> Style: ...
    @property
    def node(self) -> Node: ...
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def source(self) -> str: ...
    def sections(self) -> list[NumPySection]: ...
    def deprecation(self) -> NumPyDeprecation | None: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def walk(self) -> DocstringWalker: ...
    def line_col(self, offset: int) -> LineColumn:
        """Convert a byte offset to a LineColumn.

        The offset is typically ``token.range.start`` or ``token.range.end``.
        ``lineno`` is 1-based; ``col`` is 0-based Unicode codepoints.
        """
        ...

# ─── Plain ───────────────────────────────────────────────────────────────────

class PlainDocstring:
    @property
    def kind(self) -> SyntaxKind: ...
    @property
    def style(self) -> Style: ...
    @property
    def node(self) -> Node: ...
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def source(self) -> str: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def walk(self) -> DocstringWalker: ...
    def line_col(self, offset: int) -> LineColumn:
        """Convert a byte offset to a LineColumn.

        The offset is typically ``token.range.start`` or ``token.range.end``.
        ``lineno`` is 1-based; ``col`` is 0-based Unicode codepoints.
        """
        ...
# ─── Walker ──────────────────────────────────────────────────────────────────

DocstringNode = Union[Node, Token]

class DocstringWalker:
    def __iter__(self) -> Iterator[DocstringNode]: ...
    def __next__(self) -> DocstringNode: ...
# ─── Model IR ────────────────────────────────────────────────────────────────

class Deprecation:
    version: str
    description: str | None
    def __init__(
        self,
        version: str,
        *,
        description: str | None = None,
    ) -> None: ...

class Parameter:
    names: list[str]
    type_annotation: str | None
    description: str | None
    is_optional: bool
    default_value: str | None
    def __init__(
        self,
        names: list[str],
        *,
        type_annotation: str | None = None,
        description: str | None = None,
        is_optional: bool = False,
        default_value: str | None = None,
    ) -> None: ...

class Return:
    name: str | None
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        *,
        name: str | None = None,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...

class ExceptionEntry:
    type_name: str
    description: str | None
    def __init__(
        self,
        type_name: str,
        *,
        description: str | None = None,
    ) -> None: ...

class SeeAlsoEntry:
    names: list[str]
    description: str | None
    def __init__(
        self,
        names: list[str],
        *,
        description: str | None = None,
    ) -> None: ...

class Reference:
    number: str | None
    content: str | None
    def __init__(
        self,
        *,
        number: str | None = None,
        content: str | None = None,
    ) -> None: ...

class Attribute:
    name: str
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        name: str,
        *,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...

class Method:
    name: str
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        name: str,
        *,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...

class Section:
    @property
    def kind(self) -> str: ...
    @property
    def parameters(self) -> list[Parameter]: ...
    @property
    def returns(self) -> list[Return]: ...
    @property
    def exceptions(self) -> list[ExceptionEntry]: ...
    @property
    def attributes(self) -> list[Attribute]: ...
    @property
    def methods(self) -> list[Method]: ...
    @property
    def see_also_entries(self) -> list[SeeAlsoEntry]: ...
    @property
    def references(self) -> list[Reference]: ...
    @property
    def body(self) -> str | None: ...
    def __init__(
        self,
        kind: str,
        *,
        parameters: list[Parameter] | None = None,
        returns: list[Return] | None = None,
        exceptions: list[ExceptionEntry] | None = None,
        attributes: list[Attribute] | None = None,
        methods: list[Method] | None = None,
        see_also_entries: list[SeeAlsoEntry] | None = None,
        references: list[Reference] | None = None,
        body: str | None = None,
    ) -> None: ...

class Docstring:
    summary: str | None
    extended_summary: str | None
    @property
    def deprecation(self) -> Deprecation | None: ...
    @deprecation.setter
    def deprecation(self, value: Deprecation | None) -> None: ...
    @property
    def sections(self) -> list[Section]: ...
    @sections.setter
    def sections(self, value: list[Section]) -> None: ...
    def __init__(
        self,
        *,
        summary: str | None = None,
        extended_summary: str | None = None,
        deprecation: Deprecation | None = None,
        sections: list[Section] | None = None,
    ) -> None: ...

# ─── Functions ───────────────────────────────────────────────────────────────

def parse(input: str) -> GoogleDocstring | NumPyDocstring | PlainDocstring: ...
def parse_google(input: str) -> GoogleDocstring: ...
def parse_numpy(input: str) -> NumPyDocstring: ...
def parse_plain(input: str) -> PlainDocstring: ...
def detect_style(input: str) -> Style: ...
def emit_google(doc: Docstring, base_indent: int = 0) -> str: ...
def emit_numpy(doc: Docstring, base_indent: int = 0) -> str: ...
def walk(node: Node) -> Iterator[Node | Token]: ...
