import enum
from typing import Generator, Union

class Style(enum.IntEnum):
    GOOGLE = ...
    NUMPY = ...

class TextRange:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...

class Token:
    @property
    def kind(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def range(self) -> TextRange: ...

class Node:
    @property
    def kind(self) -> str: ...
    @property
    def range(self) -> TextRange: ...
    @property
    def children(self) -> list[Union[Node, Token]]: ...

# ─── Google ──────────────────────────────────────────────────────────────────

class GoogleArg:
    @property
    def name(self) -> Token: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...

class GoogleReturns:
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class GoogleException:
    @property
    def type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class GoogleSection:
    @property
    def kind(self) -> str: ...
    @property
    def args(self) -> list[GoogleArg]: ...
    @property
    def returns(self) -> GoogleReturns | None: ...
    @property
    def exceptions(self) -> list[GoogleException]: ...
    @property
    def body_text(self) -> Token | None: ...
    @property
    def node(self) -> Node: ...

class GoogleDocstring:
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def sections(self) -> list[GoogleSection]: ...
    @property
    def node(self) -> Node: ...
    @property
    def source(self) -> str: ...
    def pretty_print(self) -> str: ...

# ─── NumPy ───────────────────────────────────────────────────────────────────

class NumPyParameter:
    @property
    def names(self) -> list[Token]: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...
    @property
    def default_value(self) -> Token | None: ...

class NumPyReturns:
    @property
    def name(self) -> Token | None: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...

class NumPyException:
    @property
    def type(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...

class NumPySection:
    @property
    def kind(self) -> str: ...
    @property
    def parameters(self) -> list[NumPyParameter]: ...
    @property
    def returns(self) -> list[NumPyReturns]: ...
    @property
    def exceptions(self) -> list[NumPyException]: ...
    @property
    def body_text(self) -> Token | None: ...
    @property
    def node(self) -> Node: ...

class NumPyDocstring:
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def sections(self) -> list[NumPySection]: ...
    @property
    def node(self) -> Node: ...
    @property
    def source(self) -> str: ...
    def pretty_print(self) -> str: ...

# ─── Functions ───────────────────────────────────────────────────────────────

def parse_google(input: str) -> GoogleDocstring: ...
def parse_numpy(input: str) -> NumPyDocstring: ...
def detect_style(input: str) -> Style: ...
def walk(node: Node) -> Generator[Node | Token, None, None]: ...
